import pandas as pd
df=pd.read_csv("Employee.csv")
#print(df)
#df1=df.groupby("Department")["Salary"].mean()
#print(df.groupby("Department")["Age"].mean())
#print(df.Salary.mean())
#f=max(df1)
#print(f)
#print(df.groupby("Department")["Salary"].sum().reset_index())
#print(df.nlargest(3,"Age")[["Department","Age"]])
#print(df.nlargest(2,"Salary")[["Department","Salary"]])
#print(df.nsmallest(3,"Age")[["Department","Age"]])
#print(df.nsmallest(2,"Salary")[["Department","Salary"]])
print(df.groupby("Department").count())
