import pandas as pd
df=pd.read_csv("Employee.csv")
#print(df)
#print(df[0:5])
#print(df.columns)
#print(len(df.columns))
#print(len(df))
#print(df["Salary"].mean())
#print(df["Salary"]<50000)
#print(df.isnull())
#print(df.duplicated())
df1=df.sort_values(by="Salary",ascending=False)
#print(df1)
print(df["Salary"])
print(df["City"])